version: 0.1
phases:
  install:
    commands:
      - echo "nothing to do in install"
  pre_build:
    commands:
      - echo "Installing dependencies - `pwd`"
      - cd app && npm install
      - cd test && npm install
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - aws cloudformation package --template-file app-sam.yaml --s3-bucket $S3_BUCKET --output-template-file app-sam-output.yaml
      - aws cloudformation package --template-file test-sam.yaml --s3-bucket $S3_BUCKET --output-template-file test-sam-output.yaml
  post_build:
    commands:
      - echo "build completed on `date`"
artifacts:
  files:
    - app-sam-output.yaml
    - test-sam-output.yaml
  discard-paths: yes
