AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creates a function to test an api
Resources:
  SetupFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      CodeUri: test/
      Handler: setup.lambda_handler
      Description: Setup integration test
      Timeout: 10
      Environment:
        Variables:
          TEST_FUNCTION: !GetAtt TestFunction.Arn
      Policies:
        Statement:
          - Action:
              - 'codepipeline:*'
              - 'cloudformation:*'
              - 'lambda:*'
              - 'logs:*'
            Effect: Allow
            Resource: '*'

  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      CodeUri: test/
      Handler: test.lambda_handler
      Description: Execute integration test
      Timeout: 60
      Policies:
        Statement:
          - Action:
              - 'codepipeline:*'
              - 'logs:*'
            Effect: Allow
            Resource: '*'

Outputs:
  CodePipelineInvokeFunction:
    Description: Lambda Function Name to Invoke from CodePipeline
    Value: !Ref SetupFunction
