version: 0.1

phases:
  build:
    commands:
      - cd app && npm install
      - cd test && npm install
      - aws cloudformation package --template app-sam.yaml --s3-bucket $S3_BUCKET --output-template template-export.yml
      - aws cloudformation package --template test-sam.yaml --s3-bucket $S3_BUCKET --output-template test-template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
    - test-template-export.yml
